//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Aporte
    {
        public int idAporte { get; set; }
        public decimal puntaje { get; set; }
        public decimal valor { get; set; }
        public decimal ponderado { get; set; }
        public int idCalificacion { get; set; }
        public string nombre { get; set; }

        [JsonIgnore]
        public virtual Calificacion Calificacion { get; set; }
    }
}
