//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Carrera
    {
        [ScaffoldColumn(false)]
        public int idCarrera { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string director { get; set; }
        public int creditos_totales { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string mision { get; set; }
        public string vision { get; set; }
        public string modalidad { get; set; }
        public string estatus { get; set; }
        public int duracion { get; set; }
        public string resolucion_ces { get; set; }
        public int semanas_periodo { get; set; }
        public string requisitos { get; set; }
        public string escenarios_labo { get; set; }
        public string objeto_estudio { get; set; }
    }
}
