//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matricula()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
        [ScaffoldColumn(false)]
        public int idmatricula { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Matricula")]
        public System.DateTime fecha { get; set; }
        [Required]
        [Column(TypeName = "decimal(18,6)")]
        [Display(Name = "Costo")]
        public decimal costo { get; set; }
        [Required(ErrorMessage = "El Estado es requerido")]
        [Display(Name = "Estado")]
        public string estado { get; set; }
        [Required(ErrorMessage = "El Tipo es requerido")]
        [Display(Name = "Tipo")]
        public string tipo { get; set; }
        [Required(ErrorMessage = "El Alumno es requerido")]
        [Display(Name = "Alumno")]
        public int idalumno { get; set; }
        [Required(ErrorMessage = "La Materia es requerida")]
        [Display(Name = "Materia")]
        public int idmateria { get; set; }
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
